title: Nancy Munoz # your name (or website title) here
logo: "images/1682990105755.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about data! <br><br>
  ðŸ“Š Former educator turned data enthusiast. Let's connect! <br><br>
  <a href="www.linkedin.com/in/nancy-munoz-data">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
